Repository project-PODA/PODA, pull requests merged in 2023-10, with the labels that each got.

#2 [UI]: asset-icon 폴더명 iconImage로 수정
  PODA/PODA/Resource/Assets.xcassets/IconImage/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/icon-eye.filled.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.imageset/icon-eye.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_photoGallery.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_photoGallery.imageset/Vector.png
Labels: UI

#4 [MERGE]: piecePage UI 구현, realm 저장 기능 구현
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Util/Extension/Date + Extension.swift
  PODA/PODA/Resource/Support/Info.plist
  PODA/PODA/Screen/Piece/Model/PieceImageModel.swift
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
  PODA/PODA/Screen/Piece/ViewController/TestPageViewController.swift
Labels: UI, FIX, FEAT

#5 [MERGE]: HomeViewController, HomeMenuViewController-홈페이지 UI 구현
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_bookMark.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_bookMark.imageset/icon_bookMark.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_diary.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_diary.imageset/icon_diary.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_finger.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_finger.imageset/icon_finger.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_piece.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_piece.imageset/icon_piece.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_qr.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_qr.imageset/icon_qr.png
  PODA/PODA/Resource/Assets.xcassets/Vector.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/Vector.imageset/Vector.png
  PODA/PODA/Resource/Support/SceneDelegate.swift
  PODA/PODA/Screen/Home/Cell/DiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeMenuViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomePieceViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: UI

#7 [MERGE]: tabbar-UI구현, scene delegate수정, asset 아이콘 이미지 추가
  PODA/PODA/Global/Base/BaseTabbarController.swift
  PODA/PODA/Global/Base/CustomTabBarController.swift
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_home.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_home.imageset/icon_home.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_home.selected.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_home.selected.imageset/icon_home.selected.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_person.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_person.imageset/icon_person.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_person.selected.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_person.selected.imageset/icon_person.selected.png
  PODA/PODA/Resource/Support/SceneDelegate.swift
Labels: UI

#9 [MERGE]: 마이페이지-UI
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_info.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_info.imageset/icon_info.png
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewModel/InfoViewModel.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewModel/ProfileViewModel.swift
  PODA/PODA/Screen/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: UI

#11 [MERGE]: develop_test
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_info.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_info.imageset/icon_info.png
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewModel/InfoViewModel.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewModel/ProfileViewModel.swift
  PODA/PODA/Screen/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: SETTING

#12 [MERGE]: SMTP 기능 추가
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Parser/HTMLParser.swift
  PODA/PODA/Network/Email/Error/SMTPError + Enum.swift
  PODA/PODA/Network/Email/InquireManager.swift
  PODA/PODA/Network/Email/SMTPManager.swift
Labels: FEAT

#13 [MERGE]: RealmManager로 로컬 파일 관리
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
  PODA/PODA/Screen/Piece/ViewController/TestPageViewController.swift
Labels: FIX, FEAT

#14 [MERGE]: 추억 다이어리 더보기, 추억 조각들 더보기, 상세 페이지 UI 구현
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Resource/Assets.xcassets/example.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/example.imageset/example.png
  PODA/PODA/Resource/Assets.xcassets/image_background.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/image_background.imageset/image_background.png
  PODA/PODA/Resource/Assets.xcassets/image_background2.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/image_background2.imageset/image_background2.png
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/Cell/DiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/DiaryDetailCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/PieceCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeMenuViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomePieceViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
Labels: UI, DOCS

#15 [MERGE]: infoPage-UI 수정 및 개인정보처리방침, 오류신고 페이지 연결
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back.imageset/3.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back.imageset/icon_back.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back.imageset/icon_back1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_disclosure.imageset/1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_disclosure.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_disclosure.imageset/Vector.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_disclosure.imageset/icon_disclosure.png
  PODA/PODA/Screen/Info/ViewController/InfoCell.swift
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
Labels: UI, FEAT

#16 [MERGE]: 다이어리 만들기 UI 및 일부 기능 구현
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_background.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_background.imageset/mingcute_paint-fill.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_background.imageset/mingcute_paint-fill@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_background.imageset/mingcute_paint-fill@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_deletePage.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_deletePage.imageset/icon-deletePage.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_deletePage.imageset/icon-deletePage@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_deletePage.imageset/icon-deletePage@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_gallery.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_gallery.imageset/solar_gallery-add-bold.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_gallery.imageset/solar_gallery-add-bold@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_gallery.imageset/solar_gallery-add-bold@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_sticker.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_sticker.imageset/solar_sticker-circle-bold.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_sticker.imageset/solar_sticker-circle-bold@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_sticker.imageset/solar_sticker-circle-bold@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_text.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_text.imageset/fluent_text-12-filled.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_text.imageset/fluent_text-12-filled@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_text.imageset/fluent_text-12-filled@3x.png
  PODA/PODA/Screen/Diary/View/Cell/Color/ColorCollectionViewCell.swift
  PODA/PODA/Screen/Diary/View/Cell/Color/ColorCollectionViewCell.xib
  PODA/PODA/Screen/Diary/View/Cell/Font/FontCollectionViewCell.swift
  PODA/PODA/Screen/Diary/View/Cell/Font/FontCollectionViewCell.xib
  PODA/PODA/Screen/Diary/View/Cell/Page/PageCollectionViewCell.swift
  PODA/PODA/Screen/Diary/View/Cell/Page/PageCollectionViewCell.xib
  PODA/PODA/Screen/Diary/View/Cell/Sticker/StickerCollectionViewCell.swift
  PODA/PODA/Screen/Diary/View/Cell/Sticker/StickerCollectionViewCell.xib
  PODA/PODA/Screen/Diary/View/Color/ColorPaletteView.swift
  PODA/PODA/Screen/Diary/View/DiaryNavigationBar.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/SelectRatioViewController.swift
  PODA/PODA/Screen/Diary/ViewController/StickerViewController.swift
  PODA/PODA/Screen/Diary/ViewModel/CreateDiaryViewModel.swift
Labels: UI, FEAT

#17 [MERGE]로그인관련 파이어베이스 연동
  PODA/PODA/Global/Base/BaseNavigationController.swift
  PODA/PODA/Global/Base/BaseTabbarController.swift
  PODA/PODA/Global/Model/UserInfo.swift
  PODA/PODA/Global/Util/Extension/Component/UICollectionView + Extension.swift
  PODA/PODA/Global/Util/Extension/Component/UITableView + Extension.swift
  PODA/PODA/Network/Email/SMTPManager.swift
  PODA/PODA/Network/Firebase/FirebaseAuthManager.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Network/Firebase/FirestorageImageManager.swift
  PODA/PODA/Network/UserDefault/UserDefaultManager.swift
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_apple.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_apple.imageset/Group 166.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_apple.imageset/Group 167.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_apple.imageset/icon_apple.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_google.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_google.imageset/Group 165.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_google.imageset/Group 166.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_google.imageset/icon_google.png
  PODA/PODA/Resource/Support/SceneDelegate.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
  PODA/PODA/Screen/SignUp/CompleteSignUpViewController.swift
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: SETTING, FEAT

#18 [MERGE]: 프로필 화면 파이어베이스 데이터 연동
  PODA/PODA/Global/Model/UserInfo.swift
  PODA/PODA/Global/Model/diaryInfo.swift
  PODA/PODA/Global/Util/Extension/Component/UIViewController + Extension.swift
  PODA/PODA/Network/Firebase/FirebaseAuthManager.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Network/Firebase/FirestorageImageManager.swift
  PODA/PODA/Network/Firebase/NetworkError/FirebaseError + Enum.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: UI, FEAT

#19 [MERGE]: infoPage 각 셀별로 UI 구성 완료, UIFont, Palette 수정
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/DesignSystem/Palette + Enum.swift
  PODA/PODA/Global/DesignSystem/UIFont + Enum.swift
  PODA/PODA/Screen/Info/NoticeModel.swift
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewController/LeaveViewController.swift
  PODA/PODA/Screen/Info/ViewController/NoticeCell.swift
  PODA/PODA/Screen/Info/ViewController/NoticeViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: UI, SETTING, CHORE

#20 [MERGE]: PiecePage UI 수정
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FIX

#21 [MERGE] enum PodaFont에 case 추가 및 상세 페이지 페이지 전환 스크롤 변경
  PODA/PODA/Global/DesignSystem/UIFont + Enum.swift
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/Cell/DiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/DiaryDetailCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/PieceCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
Labels: UI, SETTING, FIX, FEAT

#22 [FIX]: 키보드 리턴키를 누르거나 바깥 화면 터치했을 때 내려가도록
  PODA/PODA/Global/Util/Extension/Component/UITextField + Extension.swift
  PODA/PODA/Global/Util/Extension/Component/UIViewController + Extension.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: FIX

#23 [MERGE]: 탈퇴하기기능, 버전 프로젝트기준으로 연동, 공지사항 연동
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Model/NoticeInfo.swift
  PODA/PODA/Global/Model/UserInfo.swift
  PODA/PODA/Global/Model/diaryInfo.swift
  PODA/PODA/Global/Util/Extension/Component/UIViewController + Extension.swift
  PODA/PODA/Global/Util/Extension/Date + Extension.swift
  PODA/PODA/Network/Firebase/FirebaseAuthManager.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Network/Firebase/FirestorageImageManager.swift
  PODA/PODA/Screen/Info/NoticeModel.swift
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewController/LeaveViewController.swift
  PODA/PODA/Screen/Info/ViewController/NoticeViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: FEAT

#24 [FEAT]: DetailDiaryPage-글자수제한
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
Labels: FEAT

#25 [FIX]: DetailDiaryViewController-글자수제한 코드 수정
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
Labels: FIX

#26 [MERGE]: 로딩인디케이터 UI 수정
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Util/CustomLoadingIndicator.swift
  PODA/PODA/Global/Util/Extension/Component/CustomLoadingIndicator.swift
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back_podaBlue.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back_podaBlue.imageset/icon-back_1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back_podaBlue.imageset/icon-back_2.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_back_podaBlue.imageset/icon-back_3.png
  PODA/PODA/Screen/Info/ViewController/LeaveViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: UI

#27 [MERGE]: smtp 양식 UI 수정
  PODA/PODA/Global/Parser/HTMLParser.swift
Labels: UI

#28 [MERGE]: 이동, 확대, 축소, 회전 구현 및 파이어베이스 연동
  PODA/PODA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PODA/PODA/Global/Model/diaryInfo.swift
  PODA/PODA/Global/Util/Extension/Component/UIView + Extension.swift
  PODA/PODA/Global/Util/Extension/Component/UIViewController + Extension.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Network/Firebase/FirestorageImageManager.swift
  PODA/PODA/Screen/Diary/View/DiaryNavigationBar.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/SelectRatioViewController.swift
Labels: FEAT

#29 [Merge]: InfoPage-메일보내기 기능 구현 및 안내멘트 세팅
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewController/NoticeViewController.swift
Labels: FEAT

#30 [MERGE]: 홈페이지, 상세페이지 데이터 연동 및 이미지 저장 기능 구현
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example1.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example1.imageset/piece_example1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example2.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example2.imageset/piece_example2.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example3.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example3.imageset/piece_example3.png
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Home/Cell/DiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/DiaryDetailCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/PieceCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
Labels: UI, FEAT, CHORE

#33 [MERGE]: 데이터 연동 및 일부 버그 수정
  PODA/PODA/Network/Firebase/FirebaseAuthManager.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Network/Firebase/NetworkError/FirebaseError + Enum.swift
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
Labels: UI, FIX, FEAT

#35 [MERGE]: 접근 분기별 카메라, 사진라이브러리 접근 권한 요청
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Resource/Support/Info.plist
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
Labels: FIX

#36 [MERGE]: 다이어리 저장 시 이미지 사이즈 축소, 오늘의 타임캡슐에 추억 조각 랜덤하게 나타나도록 구현
  PODA/PODA/Global/Util/Extension/Component/UIView + Extension.swift
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/Cell/PieceCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: UI, FEAT

#38 [MERGE]: LoginPage-눈 아이콘 변경, 간편로그인 아이콘 주석처리
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/icon-eye.filled.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/icon_eye.filled_1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/icon_eye.filled_2png.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_eye.filled.imageset/icon_eye.filled_3.png.png
  PODA/PODA/Screen/Login/LoginViewController.swift
Labels: UI

#37 [MERGE]: InfoPage-메일, 프로필, 공지사항 수정
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Base/BaseTabbarController.swift
  PODA/PODA/Global/Util/Extension/UIImage.swift
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewController/NoticeCell.swift
  PODA/PODA/Screen/Info/ViewController/NoticeViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: UI, FEAT

#39 [MERGE]: 추억 다이어리 / 추억 조각 상세페이지 이미지 삭제 구현, 다이어리 제목 3줄로 표시되도록 변경
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_editCalendar.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_editCalendar.imageset/icon_editCalendar.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_editCalendar.imageset/icon_editCalendar@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_editCalendar.imageset/icon_editCalendar@3x.png
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/Cell/DiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/DiaryDetailCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: UI, FEAT

#40 [MERGE]:디버그용 간편회원가입/로그인(랜덤), 에러로그 추가
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Util/Extension/String + Extension.swift
  PODA/PODA/Global/Util/Logger/Logger.swift
  PODA/PODA/Network/Firebase/FirebaseAuthManager.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Network/Firebase/FirestorageImageManager.swift
  PODA/PODA/Network/Firebase/NetworkError/FirebaseError + Enum.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
Labels: FEAT, CHORE

#41 [MERGE]: PiecePage Alert 수정
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FIX

#42 [MERGE]: 다이어리 만들기에서 내용 미입력시 alert 띄워주는 기능 구현
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/SelectRatioViewController.swift
Labels: FEAT

#43 [MERGE]: 추억 다이어리 제목, 내용 잘림 수정, UILabel Extension 그림자 추가, 다이어리 상세 페이지 UI 수정, HomeVC 코드 정리
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Util/Extension/Component/UILabel + Extension.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash@3x.png
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/Cell/DiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/Cell/MoreDiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: BUG, UI, FIX, FEAT

#44 [MERGE]: 약관동의 페이지 추가, InfoPage에도 약관동의 셀 추가
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Base/BaseViewController.swift
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/SignUp/AgreeTermsViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: UI

#45 [MERGE]: 약관 노션 주소 설정 변경
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/SignUp/AgreeTermsViewController.swift
Labels: FIX

#46 [MERGE]: 다이어리 이미지 렌더링 코드 추가
  PODA/PODA/Global/Util/Extension/Component/UIView + Extension.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
Labels: FIX

#47 [MERGE]: color palette 오류 수정 및 homeVC에 데이터 전달 구현
  PODA/PODA/Global/Util/Extension/Date + Extension.swift
  PODA/PODA/Global/Util/Logger/Logger.swift
  PODA/PODA/Network/Firebase/FirebaseAuthManager.swift
  PODA/PODA/Network/Firebase/FirestorageDBManager.swift
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_colorPicker.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_colorPicker.imageset/colorPicker 1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_colorPicker.imageset/colorPicker 1@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_colorPicker.imageset/colorPicker 1@3x.png
  PODA/PODA/Screen/Diary/View/Color/ColorPaletteView.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FIX, FEAT

#48 [MERGE]: 다이어리 데이터 전달 방식 변경
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeMenuViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
Labels: FIX

#49 [MERGE]: qr코드 비디오 촬영 제한
  PODA/PODA/Screen/Home/ViewController/HomeMenuViewController.swift
Labels: FIX

#50 [UI]: 런치스크린
  PODA/PODA/Resource/Base.lproj/LaunchScreen.storyboard
Labels: UI

#51 [MERGE]: 실기기 테스트 후 UI 잔잔바리 수정(Trello 참고)
  PODA/PODA/Global/Util/Extension/Date + Extension.swift
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Home/Cell/MoreDiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
Labels: BUG, UI, FIX
