Repository project-PODA/PODA, pull requests merged in 2023-11, with the labels that each got.

#52 [MERGE]: 로그아웃 버튼 조금 올리기, 탈퇴후에 탈퇴 성공 알럿뷰 띄우기
  PODA/PODA/Global/Util/Extension/Component/UIViewController + Extension.swift
  PODA/PODA/Screen/Info/ViewController/LeaveViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: UI

#53 [MERGE]: 회원가입-버튼 유도, 스크롤뷰 수정, 백버튼 추가
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/SignUp/AgreeTermsViewController.swift
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
  PODA/PODA/Screen/SignUp/SignUpViewController.swift
Labels: UI

#54 [MERGE]: 텍스트필드 커서 잘리는 거 해결
  PODA/PODA/Screen/Login/LoginViewController.swift
Labels: UI

#55 [MERGE]: Realm 저장 경로 절대경로에서 상대경로로 변경
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FIX

#56 [MERGE]: iPhone SE에 맞게 수정
  PODA/PODA/Screen/Diary/View/Color/ColorPaletteView.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/SelectRatioViewController.swift
Labels: UI, FIX

#57 [MERGE]: 다이어리 만들기페이지, 프로필 페이지 앨범 접근 권한 요청
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: FIX

#58 [MERGE]: 컬러 팔레트 색상 변경
  PODA/PODA/Screen/Diary/View/Cell/Color/ColorCollectionViewCell.swift
  PODA/PODA/Screen/Diary/View/Color/ColorPaletteView.swift
Labels: UI, FEAT

#59 [MERGE]: 스티커 버튼을 추억조각 버튼으로 변경
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_pieceSticker.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_pieceSticker.imageset/solar_sticker-circle-bold.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_pieceSticker.imageset/solar_sticker-circle-bold@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_pieceSticker.imageset/solar_sticker-circle-bold@3x.png
  PODA/PODA/Screen/Diary/View/Cell/Sticker/StickerCollectionViewCell.swift
  PODA/PODA/Screen/Diary/View/Cell/Sticker/StickerCollectionViewCell.xib
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/StickerViewController.swift
Labels: UI, FIX

#60 [MERGE]: QR 스캐너 구현, 로딩 인디케이터 추가, asset 수정, 그라데이션, 버튼 위치 등 UI 수정
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_bookMark.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_bookMark.imageset/icon_bookMark.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_bookMark.imageset/icon_bookMark@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_bookMark.imageset/icon_bookMark@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_diary.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_diary.imageset/icon_diary.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_diary.imageset/icon_diary@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_diary.imageset/icon_diary@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_finger.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_finger.imageset/icon_finger.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_finger.imageset/icon_finger@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_finger.imageset/icon_finger@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_piece.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_piece.imageset/icon_piece.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_piece.imageset/icon_piece@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_piece.imageset/icon_piece@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_qr.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_qr.imageset/icon_qr.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_qr.imageset/icon_qr@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_qr.imageset/icon_qr@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example1.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example1.imageset/piece_example1.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example2.imageset/piece_example2.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example3.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/piece_example3.imageset/piece_example3.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_background.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/Images/image_background.imageset/image_background.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_gradientView.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/Images/image_gradientView.imageset/image_gradientView.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_gradientView.imageset/image_gradientView@2x.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_gradientView.imageset/image_gradientView@3x.png
  PODA/PODA/Resource/Assets.xcassets/example.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/example.imageset/example.png
  PODA/PODA/Resource/Assets.xcassets/image_background2.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/image_background2.imageset/image_background2.png
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Home/Cell/MoreDiaryCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeMenuViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/QRViewController.swift
Labels: UI, FIX, FEAT, CHORE

#61 [MERGE]: 다이어리 데이터 없을 때 로딩인디케이터 멈추는 메서드 호출
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/QRViewController.swift
Labels: BUG

#62 [MERGE]: 텍스트필드 소문자로 시작, 키보드타입 이메일로 변경
  PODA/PODA/Screen/Login/LoginViewController.swift
Labels: BUG, FIX

#63 [MERGE]: 추억 조각 날짜 변경 기능 구현, Realm에 연동
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FEAT

#64 [MERGE]: 상세페이지에서 다이어리 페이지수 제거 (다이어리 페이지 추가 기능 구현 후 다시 추가 예정)
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: UI, FIX

#65 [Setting]: 파이어베이스 서버 분리되도록 수정
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Config/GoogleService-Info-Dev.plist
  PODA/PODA/Resource/Support/AppDelegate.swift
Labels: SETTING

#66 [MERGE]: indicator 시작 시점 수정
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA.xcodeproj/xcshareddata/xcschemes/PODA.xcscheme
  PODA/PODA/Global/Config/GoogleService-Info.plist
  PODA/PODA/Network/Firebase/FirestorageImageManager.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
Labels: FIX

#67 [MERGE]: realm 추억조각 등록 날짜 추가
  PODA/PODA/Screen/Piece/Model/PieceImageModel.swift
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
Labels: FIX

#68 [MERGE]: 로그인 여부에 따라 루트뷰 변경
  PODA/PODA/Resource/Support/SceneDelegate.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
Labels: FIX

#69 [MERGE]: 추억 조각 컬렉션뷰 등록순/추억날짜순으로 정렬 기능 추가, 타임캡슐 날짜 UI 변경, 알럿뷰 통일
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA.xcodeproj/xcshareddata/xcschemes/PODA.xcscheme
  PODA/PODA/Global/Config/GoogleService-Info-Dev.plist
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/image_speechBubblePodaBlue.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/image_speechBubblePodaBlue@2x.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/image_speechBubblePodaBlue@3x.png
  PODA/PODA/Resource/Support/AppDelegate.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/SelectRatioViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: UI, FIX, FEAT

#70 PODA v1.0.1 Release
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Global/Config/GoogleService-Info-Dev.plist
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/image_speechBubblePodaBlue.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/image_speechBubblePodaBlue@2x.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_speechBubblePodaBlue.imageset/image_speechBubblePodaBlue@3x.png
  PODA/PODA/Resource/Support/SceneDelegate.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/DetailDiaryViewController.swift
  PODA/PODA/Screen/Diary/ViewController/SelectRatioViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Login/LoginViewController.swift
  PODA/PODA/Screen/Piece/Model/PieceImageModel.swift
  PODA/PODA/Screen/Piece/Model/RealmManager.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: RELEASE

#71 [MERGE]: 공지사항 셀 선택 시 체크박스 아이콘이 토글되는 애니메이션 추가
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Screen/Info/ViewController/NoticeCell.swift
Labels: FIX

#72 [MERGE]: 프로필 이미지 작게, 회원가입/탈퇴하기 숨기기
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
Labels: UI

#73 [MERGE]: 타임캡슐 날짜 위치 조정
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
Labels: FIX

#74 [MERGE]: 취소, 저장 버튼/이미지 뷰 위치 조정
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FIX

#75 [MERGE]: 삭제, 저장 버튼 아이콘으로 변경 후 위치 조정
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/icon_download.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/icon_download@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/icon_download@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash@3x.png
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
Labels: FIX

#76 [MERGE]: 오토레이아웃 오류 해결
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
Labels: FIX

#77 [MERGE]: DetailVC에서 뒤로 가기 시 이미지 멈춤 현상 해결
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
Labels: FIX

#78 [MERGE]: 버튼 타이틀 뒤로 > 취소로 수정
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: FIX

#81 [MERGE]: 추억 조각 더보기 페이지로 데이터 전달, UI 수정
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
Labels: FIX

#82 [MERGE]: 타임캡슐 이미지 눌렀을 때 동일한 이미지가 상세페이지에 나타나도록 코드 수정
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
Labels: BUG, FIX

#83 [MERGE]: Label 내용 변경
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
Labels: FIX

#84 [MERGE]: 프로필 설정 설명 라벨 삭제
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
Labels: FIX

#85 [MERGE]: 추억 조각 눌렀을 때 해당 조각의 정보가 상세페이지에 나타나도록 코드 수정
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
Labels: BUG, FIX

#86 [MERGE]: HomePage의 추억 조각 눌렀을 때 해당 조각의 정보가 상세페이지에 나타나도록 코드 수정
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
Labels: BUG, FIX

#87 [MERGE]: V1.0.2/realm migration
  PODA/PODA/Resource/Support/AppDelegate.swift
Labels: FIX, FEAT

#88 [MERGE]: 삭제 기능 구현 및 diaryView 밖으로 나간 부분은 잘려서 보이게 구현
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Screen/Diary/View/DiaryView.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
Labels: UI, FIX, FEAT

#89 [MERGE]: textView 이동할 때 키보드 내려가도록 구현
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
Labels: FEAT

#90 PODA v1.0.2 Release
  PODA/PODA.xcodeproj/project.pbxproj
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/icon_download.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/icon_download@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_download.imageset/icon_download@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_randomPiece.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_randomPiece.imageset/icon_randomPiece.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_randomPiece.imageset/icon_randomPiece@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_randomPiece.imageset/icon_randomPiece@3x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash@2x.png
  PODA/PODA/Resource/Assets.xcassets/IconImage/icon_trash.imageset/icon_trash@3x.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_bubble.imageset/Contents.json
  PODA/PODA/Resource/Assets.xcassets/Images/image_bubble.imageset/image_bubble.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_bubble.imageset/image_bubble@2x.png
  PODA/PODA/Resource/Assets.xcassets/Images/image_bubble.imageset/image_bubble@3x.png
  PODA/PODA/Resource/Support/AppDelegate.swift
  PODA/PODA/Screen/Detail/ViewController/DetailViewController.swift
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/View/DiaryView.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Home/Cell/MorePieceCollectionViewCell.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MoreDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
  PODA/PODA/Screen/Home/ViewController/PieceShakeViewController.swift
  PODA/PODA/Screen/Info/ViewController/InfoViewController.swift
  PODA/PODA/Screen/Info/ViewController/NoticeCell.swift
  PODA/PODA/Screen/Piece/ViewController/PieceShakeViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
  PODA/PODA/Screen/Profile/Profile/ViewController/ProfileViewController.swift
  PODA/PODA/Screen/SignUp/SetProfileViewController.swift
Labels: BUG, FIX, FEAT, RELEASE

#91 [MERGE]: 다이어리 저장시 이미지 테두리도 같이 저장되는 오류 수정
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
Labels: FIX

#92 [MERGE]: 선택된 추억 조각이 아닌 다른 조각이 삭제되는 오류 수정
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: BUG, FIX

#93 [MERGE]: 코드 수정
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
Labels: FIX

#94 [MERGE]: Button Configuration으로 변경
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
Labels: FIX

#95 PODA v1.0.2 Release
  PODA/PODA/Screen/Detail/ViewController/SaveDeleteViewController.swift
  PODA/PODA/Screen/Diary/ViewController/CreateDiaryViewController.swift
  PODA/PODA/Screen/Home/ViewController/HomeViewController.swift
  PODA/PODA/Screen/Home/ViewController/MorePieceViewController.swift
  PODA/PODA/Screen/Piece/ViewController/PieceViewController.swift
Labels: RELEASE
